#
# Copyright (c) 2014 Krzysztof Jusiak (krzysztof at jusiak dot net)
#
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
#

test:
	$(CXX) -Wall -Wextra -pedantic --std=c++11 mocks_injector_mt.cpp -o mocks_injector_mt -I.. -I../di/include -I../hippomocks/HippoMocks && ./mocks_injector_mt

